apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-sa
  namespace: eventora
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: eventora
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-sa
  namespace: eventora
automountServiceAccountToken: false
