apiVersion: v1
kind: Secret
metadata:
  name: eventora-secret
  namespace: eventora
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017/eventora"
  JWT_SECRET: "your_super_secret_jwt_key"
  EMAIL_USER: "your_email@example.com"
  EMAIL_PASS: "your_email_password"
